[build]
builder = "Railpack"

[build.scripts]
install = "pip install -r backend/requirements.txt"

[build.variables]
PYTHON_VERSION = "3.11"

[deploy]
startCommand = "python -m uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
