[build]
builder = "Railpack"

[build.scripts]
install = "cd backend && pip install -r requirements.txt"

[build.variables]
PYTHON_VERSION = "3.11"

[deploy]
startCommand = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
